version: '3.8'

services:
  prefect-server:
    image: prefecthq/prefect:2-latest
    ports:
      - "4200:4200"
    environment:
      - PREFECT_API_URL=http://localhost:4200/api
      - PREFECT_SERVER_API_HOST=0.0.0.0
      - PREFECT_SERVER_API_PORT=4200
    volumes:
      - prefect_data:/root/.prefect
      - ./data:/app/data
      - ./logs:/app/logs
    command: >
      bash -c "
        prefect server start --host 0.0.0.0 --port 4200
      "

  prefect-agent:
    image: prefecthq/prefect:2-latest
    environment:
      - PREFECT_API_URL=http://prefect-server:4200/api
    volumes:
      - prefect_data:/root/.prefect
      - ./workflows:/app/workflows
      - ./data:/app/data
    depends_on:
      - prefect-server
    command: >
      bash -c "
        sleep 10 &&
        prefect worker start --pool default
      "

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: prefect
      POSTGRES_USER: prefect
      POSTGRES_PASSWORD: prefect
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./configs/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  prefect_data:
  postgres_data:
  redis_data: 