version: '3.8'

services:
  dagster:
    image: dagster/dagster:latest
    ports:
      - "3000:3000"
    environment:
      - DAGSTER_HOME=/opt/dagster/dagster_home
      - DAGSTER_WEBSERVER_HOST=0.0.0.0
      - DAGSTER_WEBSERVER_PORT=3000
    volumes:
      - dagster_home:/opt/dagster/dagster_home
      - ./assets:/opt/dagster/app/assets
      - ./definitions:/opt/dagster/app/definitions
      - ./data:/opt/dagster/app/data
      - ./configs:/opt/dagster/app/configs
    working_dir: /opt/dagster/app
    command: >
      bash -c "
        dagster dev --host 0.0.0.0 --port 3000
      "

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: dagster
      POSTGRES_USER: dagster
      POSTGRES_PASSWORD: dagster
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./configs/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  dagster-daemon:
    image: dagster/dagster:latest
    environment:
      - DAGSTER_HOME=/opt/dagster/dagster_home
    volumes:
      - dagster_home:/opt/dagster/dagster_home
      - ./assets:/opt/dagster/app/assets
      - ./definitions:/opt/dagster/app/definitions
      - ./data:/opt/dagster/app/data
    depends_on:
      - dagster
    command: >
      bash -c "
        sleep 10 &&
        dagster-daemon run
      "

volumes:
  dagster_home:
  postgres_data:
  redis_data: 