# Prefect Configuration for Local Deployment
name: "prefect-3-local"
description: "Local Prefect deployment for data engineering demos"

# Work pools configuration
work_pools:
  - name: "default"
    description: "Default work pool for local execution"
    work_queues:
      - name: "default"
        description: "Default work queue"
        concurrency_limit: 10

# Deployments configuration
deployments:
  - name: "data-pipeline"
    description: "Basic ETL data pipeline"
    entrypoint: "workflows/data_pipeline.py:data_pipeline"
    work_pool:
      name: "default"
      work_queue_name: "default"
    schedule:
      cron: "0 2 * * *"  # Daily at 2 AM
    tags: ["etl", "pipeline", "daily"]
    
  - name: "etl-workflow"
    description: "Complex ETL workflow with multiple data sources"
    entrypoint: "workflows/etl_workflow.py:etl_workflow"
    work_pool:
      name: "default"
      work_queue_name: "default"
    schedule:
      cron: "0 4 * * *"  # Daily at 4 AM
    tags: ["etl", "complex", "analytics"]
    
  - name: "scheduled-workflow"
    description: "Scheduled daily data processing workflow"
    entrypoint: "workflows/scheduled_workflow.py:scheduled_daily_workflow"
    work_pool:
      name: "default"
      work_queue_name: "default"
    schedule:
      cron: "0 6 * * *"  # Daily at 6 AM
    tags: ["scheduled", "daily", "monitoring"]

# Storage configuration
storage:
  type: "local"
  path: "./data"
  options:
    base_path: "./data"

# Logging configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  handlers:
    - type: "file"
      filename: "./logs/prefect.log"
      level: "INFO"
    - type: "console"
      level: "INFO"

# Notifications configuration
notifications:
  - name: "workflow-completion"
    description: "Notify on workflow completion"
    type: "email"
    config:
      recipients: ["admin@example.com"]
      subject_template: "Workflow {flow_name} completed"
      body_template: |
        Workflow {flow_name} completed with status {state_name}.
        
        Run details:
        - Flow run ID: {flow_run_id}
        - Start time: {start_time}
        - End time: {end_time}
        - Duration: {duration}

# Monitoring configuration
monitoring:
  enabled: true
  metrics:
    - name: "workflow_duration"
      description: "Workflow execution duration"
      type: "histogram"
    - name: "task_success_rate"
      description: "Task success rate"
      type: "gauge"
    - name: "data_processed"
      description: "Amount of data processed"
      type: "counter"

# Security configuration
security:
  api_key_expiration_days: 30
  session_timeout_minutes: 60
  max_login_attempts: 5

# Performance configuration
performance:
  max_concurrent_flows: 10
  max_concurrent_tasks: 50
  task_timeout_seconds: 3600
  flow_timeout_seconds: 7200

# Development settings
development:
  debug_mode: false
  hot_reload: true
  auto_deploy: true 