# Manual trigger test 2024-06-12
name: Compose & Lint

on:
  push:
    paths:
      - '**/docker-compose.yml'
      - '**/Dockerfile'
      - '**/*.yml'
      - '**/*.yaml'
      - '.github/workflows/compose-lint.yml'
  pull_request:
    paths:
      - '**/docker-compose.yml'
      - '**/Dockerfile'
      - '**/*.yml'
      - '**/*.yaml'
      - '.github/workflows/compose-lint.yml'

jobs:
  compose-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install yamllint & hadolint
        run: |
          pip install --quiet yamllint
          sudo wget -qO /usr/local/bin/hadolint \
              https://github.com/hadolint/hadolint/releases/latest/download/hadolint-Linux-x86_64
          sudo chmod +x /usr/local/bin/hadolint

      # ───────── Lint Dockerfiles ─────────
      - name: Lint Dockerfiles (fail only on errors)
        run: |
          set -o pipefail
          # hadolint: --failure-threshold error → exit 1 only on error severity
          find . -type f -iname 'Dockerfile' | while read f; do
            echo "▶️  hadolint $f"
            hadolint --failure-threshold error "$f" || true
          done

      # ───────── Lint YAML ─────────
      - name: Lint YAML (warnings allowed)
        run: |
          run: yamllint .
        # yamllint exits 1 on error by default; relaxed preset keeps most issues at warning-level

      # ───────── Validate compose files ─────────
      - name: Validate docker-compose files
        run: |
          find . -type f -iname 'docker-compose.yml' | while read f; do
            echo "▶️  docker compose -f $f config"
            docker compose -f "$f" config >/dev/null
          done
